### ISSUE TITLE
[feature request] Better name generation for kebab case attributes

### ISSUE THREAD

**Issue by phdoerfler** [eed3si9n/scalaxb#655]
Currently, XML attributes with hyphens, e.g., `tester-pk`:

```xml
<xs:attribute name="tester-pk" type="xs:string" use="required"/>
```

result in generated names containing "u45", e.g. `testeru45pk`:

```scala
lazy val testeru45pk = attributes("@tester-pk").as[String]
```

In comparison, JAXB, by default, understands this attribute name to be multiple words in kebab case and generates camel case identifiers:

```java
@XmlAttribute(name = "tester-pk", required = true)
protected String testerPk;
…
public String getTesterPk() { return testerPk; }
```

I was unable to find a way to coerce scalaxb to behave like this.

I propose that:
- scalaxb treats "-" in attribute names like jaxb does by default, and
- it offers ways to customize the name generation, e.g., through a function `String => String` or similar and/or
- an option specific for "-"

Thoughts?

**Comment by eed3si9n** [comment]
There seems to be two related settings as precedence:

https://github.com/eed3si9n/scalaxb/blob/e242798464468e1eb38b78401ff49f79420a968e/sbt-scalaxb/src/main/scala/sbtscalaxb/ScalaxbKeys.scala#L51-L52

Rather than a general function, which might be difficult to configure via Maven or CLI, probably adding a specific setting to convert identifiers into camelCase kind of makes sense?

**Comment by phdoerfler** [comment]
Indeed, `SymbolEncodingStrategy.Discard` does the trick, thanks! As far as I'm concerned that's sufficient. I wouldn't mind an additional specific setting to convert to camelCase, too. But for now the existing settings seem adequate.

**Comment by phdoerfler** [comment]
Indeed, hat does the trick, thanks! As far as I am concerend, that solution is sufficient for now.
